# .github/workflows/ios-unsigned.yml
name: Build Unsigned iOS IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install CocoaPods (if needed)
        run: |
          cd ios && pod install || true
          cd ..

      - name: Clean and archive without signing
        run: |
          xcodebuild clean archive \
            -workspace ios/bitchat.xcworkspace \
            -scheme bitchat \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/bitchat.xcarchive \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO

      - name: Export unsigned IPA
        run: |
          mkdir -p build/unsigned
          xcodebuild -exportArchive \
            -archivePath build/bitchat.xcarchive \
            -exportPath build/unsigned \
            -exportOptionsPlist ios/ExportOptions.plist \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO

      - name: Package unsigned .ipa
        run: |
          cd build/unsigned
          cp -R bitchat.app Payload/
          zip -r bitchat-unsigned.ipa Payload
          mv bitchat-unsigned.ipa ../

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v3
        with:
          name: bitchat-unsigned.ipa
          path: build/bitchat-unsigned.ipa