name: Build iOS IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "16.2.0"

    - name: Install dependencies
      run: |
        brew install xcodegen
        xcodegen generate

    - name: Build IPA
      run: |
        set -o pipefail && xcodebuild \
          -scheme bitchat_iOS \
          -sdk iphoneos \
          -configuration Release \
          -archivePath ${{ github.workspace }}/build/bitchat.xcarchive archive \
          CODE_SIGN_STYLE=Automatic \
          DEVELOPMENT_TEAM=L3N5LHJD5Y \
          PROVISIONING_PROFILE_SPECIFIER="" \
          | xcpretty

        xcodebuild -exportArchive \
          -archivePath ${{ github.workspace }}/build/bitchat.xcarchive \
          -exportPath ${{ github.workspace }}/build \
          -exportOptionsPlist ${{ github.workspace }}/ExportOptions.plist \
          | xcpretty

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: bitchat.ipa
        path: ${{ github.workspace }}/build/*.ipa
